import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google" 
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/footer" 
import Navbar from "@/components/navbar"
import StructuredData from "@/components/structured-data"


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <StructuredData />
          <div className="flex min-h-screen flex-col">
            <Navbar />
            {children}
            </div>
           <Footer />  
        </ThemeProvider>
      </body>
    </html>
  );
}
